### ISSUE TITLE
与ltablex冲突

### ISSUE THREAD

**Issue by chenboshuo** [latexstudio/CUMCMThesis#13]
在使用`ltablex``之后模板显示异常
![image](https://user-images.githubusercontent.com/43953268/91171807-b83fc700-e70d-11ea-96c7-6595dcccfb6e.png)

不同的代码片段如下

%% booktabs 提供了\toprule 等命令.
\RequirePackage{booktabs}
% 表格自动换行
\RequirePackage{tabularx}
\RequirePackage{ltablex}

请问是发生什么问题了

**Comment by chenboshuo** [comment]
看了官方文档，ltablex 重新定义 `tabularx` 环境，`\keepXColumns`可以取消重载命令
```latex
\keepXColumns\begin{tabularx}{\textwidth}{cXcX@{}}
\mcm@numberpage@string@headname & & \mcm@numberpage@string@allcountrynum&\\[-5pt]
\mcm@numberpage@string@headnameb & &\mcm@numberpage@string@allcountrynumb&\\
\cline{2-2}\cline{4-4}
\end{tabularx}
```

**Comment by latexstudio** [comment]
最好用通用的环境吧，考虑新的，总会各种兼容性问题。
