### ISSUE TITLE
cumcmthesis、mdframed、subcaption都出现not found怎么办

### ISSUE THREAD

**Issue by taotie123742** [latexstudio/CUMCMThesis#21]
\documentclass[withoutpreface,bwprint]{cumcmthesis} 
\usepackage[framemethod=TikZ]{mdframed}
\usepackage{subcaption}
以上代码中的cumcmthesis、mdframed、subcaption都出现not found怎么办

**Comment by taotie123742** [comment]
已解决

**Comment by CamuseCao** [comment]
Done
