### ISSUE TITLE
这个repo还在维护吗？

### ISSUE THREAD

**Issue by ZJsheep** [latexstudio/CUMCMThesis#27]
如果不维护了，有没有大佬教一下怎么把前两页那个 2021 改成 2022 以便今年使用

**Comment by FvNCCR228** [comment]
> 如果不维护了，有没有大佬教一下怎么把前两页那个 2021 改成 2022 以便今年使用

cls文件 599行 有一个 `\the\year` 如果不行直接换成2022
不过这个命令获取的是当前时间啊 怎么会出问题

**Comment by ZJsheep** [comment]
谢谢大佬解答，确实是我电脑时间不对
