### ISSUE TITLE
Package fontspec Error: The font "SimSun" cannot be found.

### ISSUE THREAD

**Issue by Lucius-lsr** [latexstudio/CUMCMThesis#8]
Package fontspec Error: The font "SimSun" cannot be found.
出现这个问题是因为没有下载最新的latex套装吗？

**Comment by CamuseCao** [comment]
应该不是。你用的是 Mac 的电脑吗？ Windows 系统是带这个字体的。Mac 的电脑上没有 SimSun 字体，你需要把字体设置改成 Mac下的对应的。打开 `cumcmthesis.cls` 文件，搜索 `SimSun` ，将其替换成 Mac 下面对应的字体。如果其它字体找不到原因可能差不多，自行替换就可以了。

**Comment by Lucius-lsr** [comment]
确实是mac电脑的问题，已解决。Mac电脑上编译这个tex文件，有些字体可以补充下载https://fontzone.net/
仍然无法解决可能需要修改/usr/local/texlive/2019/texmf-dist/tex/latex/ctex/fontset下面的ctex-fontset-windowsnew.def和ctex-fontset-windowsold.def文件

**Comment by CamuseCao** [comment]
`def` 文件不建议用户自己修改，还是推荐 `XeCJK` 宏包来设定你的字体。

**Comment by FweiI** [comment]
我是windows 为什么也遇到了
