### ISSUE TITLE
放到overleaf编译Timeout

### ISSUE THREAD

**Issue by jjyAmongCookie** [latexstudio/CUMCMThesis#9]
1. 啥都不管，放到overleaf编译timeout
2. 设置Xelatex编译后，报错不能使用snakes包，改用decorations包，改好了之后仍然报错
```Package hyperref Warning: Rerun to get /PageLabels entry```
不知道怎么解决

**Comment by CamuseCao** [comment]
现在下载 [dev](https://github.com/latexstudio/CUMCMThesis/tree/dev) 分支的模板拿到 overleaf 已经能够直接编译了，未来会合并到主分支。
